/**
 * Bill of materials for a library system (PB-791).
 *
 *   npx tsx scripts/bom.ts quadcopter-5in
 *
 * Walks the system tree (children × quantity, through assemblies, groups and
 * harnesses) and writes library/systems/<id>/generated/bom.{md,json}. Each
 * row carries the part's primary manufacturer source and its committed
 * verification summary, so every line can be traced.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import { join } from "path";
import { fileURLToPath, pathToFileURL } from "url";
import type { ModuleDef } from "../src/types/index.js";
import type { ModuleLookup } from "../src/system/index.js";

const ROOT = fileURLToPath(new URL("..", import.meta.url));

interface BomRow {
  line: number;
  partId: string;
  name: string;
  manufacturer?: string;
  partNumber?: string;
  quantity: number;
  /** Units per retail pack, when the part is sold in packs. */
  packQuantity?: number;
  buy: "purchase" | "included" | "fabricate";
  includedWith?: string;
  usedBy: string[];
  source?: string;
  verification?: string;
  assumptions: number;
  openGaps: number;
}

function trait(def: ModuleDef, type: string, key: string): unknown {
  for (const t of def.traits ?? []) {
    const params = t.params as Record<string, unknown> | undefined;
    if (t.type === type && params && key in params) return params[key];
  }
  return undefined;
}

function evidence(partId: string, def?: ModuleDef): { source?: string; verification?: string; assumptions: number; openGaps: number } {
  const dir = join(ROOT, "library", "parts", partId);
  // system-level hardware without a research folder cites its supplier listing in a usage_note
  let source: string | undefined = def?.traits?.find((t) => t.type === "usage_note" && typeof t.params?.source === "string")?.params?.source as string | undefined;
  if (existsSync(join(dir, "sources.json"))) {
    const rows = JSON.parse(readFileSync(join(dir, "sources.json"), "utf8")) as Array<Record<string, unknown>>;
    source = String((rows.find((r) => r.authority === "manufacturer") ?? rows[0])?.url ?? "");
  }
  if (!existsSync(join(dir, "verification.json"))) {
    const count = (type: string) => def?.traits?.filter((t) => t.type === type).length ?? 0;
    return { source, assumptions: count("assumption"), openGaps: count("data_gap") };
  }
  const v = JSON.parse(readFileSync(join(dir, "verification.json"), "utf8"));
  return {
    source,
    verification: v.audit ? `audited ${v.audit.confirmed}/${v.audit.checked}` : "not audited",
    assumptions: v.assumptions?.length ?? 0,
    openGaps: v.data_gaps?.length ?? 0,
  };
}

export function buildBom(system: ModuleDef, lookup: ModuleLookup): BomRow[] {
  const rows = new Map<string, BomRow>();

  const visit = (def: ModuleDef, multiplier: number, path: string) => {
    for (const ref of def.children ?? []) {
      const child = lookup(ref.moduleDefId);
      if (!child) throw new Error(`${path}/${ref.id}: unknown module ${ref.moduleDefId}`);
      const qty = multiplier * (ref.quantity ?? 1);
      const childPath = path ? `${path}/${ref.id}` : ref.id;
      if (child.children?.length) {
        // assemblies, groups and harness kits: their contents are the line items
        visit(child, qty, childPath);
        continue;
      }
      const includedWith = trait(child, "usage_note", "included_with") as string | undefined;
      const custom = /\(custom\)/i.test(child.manufacturer ?? "");
      const row = rows.get(child.id) ?? {
        line: 0,
        partId: child.id,
        name: child.name,
        manufacturer: child.manufacturer,
        partNumber: child.part_number,
        quantity: 0,
        packQuantity: trait(child, "performance", "pack_quantity") as number | undefined,
        buy: custom ? "fabricate" : includedWith ? "included" : "purchase",
        includedWith,
        usedBy: [],
        ...evidence(child.id, child),
      };
      row.quantity += qty;
      row.usedBy.push(childPath);
      rows.set(child.id, row);
    }
  };
  visit(system, 1, "");

  const order = { purchase: 0, fabricate: 1, included: 2 };
  return [...rows.values()]
    .sort((a, b) => order[a.buy] - order[b.buy] || a.name.localeCompare(b.name))
    .map((row, i) => ({ ...row, line: i + 1 }));
}

export function bomMarkdown(system: ModuleDef, rows: BomRow[]): string {
  const packs = (r: BomRow) => (r.packQuantity ? ` (${Math.ceil(r.quantity / r.packQuantity)} pack of ${r.packQuantity})` : "");
  const lines = [
    `# Bill of materials — ${system.name}`,
    "",
    `Generated by \`npx tsx scripts/bom.ts\` from \`library/systems/${system.id.replace(/^quadcopter-5in$/, "quadcopter-5in")}\`. Do not edit by hand.`,
    "",
    "| # | Part | Manufacturer | Part number | Qty | Supply | Verification | Assumptions / open gaps | Source |",
    "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ...rows.map((r) =>
      [
        r.line,
        `${r.name} (\`${r.partId}\`)`,
        r.manufacturer ?? "",
        r.partNumber ?? "",
        `${r.quantity}${packs(r)}`,
        r.buy === "included" ? `included with \`${r.includedWith}\`` : r.buy,
        r.verification ?? "not audited",
        `${r.assumptions} / ${r.openGaps}`,
        r.source ? `[link](${r.source})` : "none",
      ].join(" | ").replace(/^/, "| ").replace(/$/, " |"),
    ),
    "",
    `Purchased lines: ${rows.filter((r) => r.buy === "purchase").length}. Fabricated: ${rows.filter((r) => r.buy === "fabricate").map((r) => r.name).join(", ") || "none"}. Included with other parts: ${rows.filter((r) => r.buy === "included").length}.`,
    "",
  ];
  return lines.join("\n");
}

async function main() {
  const id = process.argv[2];
  if (!id) throw new Error("usage: npx tsx scripts/bom.ts <system-id>");
  const dir = join(ROOT, "library", "systems", id);
  const mod = (await import(pathToFileURL(join(dir, "index.ts")).href)) as { SYSTEM: ModuleDef; lookup: ModuleLookup };
  const rows = buildBom(mod.SYSTEM, mod.lookup);
  const unsourced = rows.filter((r) => r.buy === "purchase" && !r.source);
  mkdirSync(join(dir, "generated"), { recursive: true });
  writeFileSync(join(dir, "generated", "bom.json"), JSON.stringify(rows, null, 2) + "\n");
  writeFileSync(join(dir, "generated", "bom.md"), bomMarkdown(mod.SYSTEM, rows));
  console.log(`${rows.length} lines written to library/systems/${id}/generated/bom.{md,json}`);
  if (unsourced.length) {
    console.error(`purchased lines without a source: ${unsourced.map((r) => r.partId).join(", ")}`);
    process.exit(1);
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) main();
